export const puppyData = [
  // Original 4
  {
    name: 'Samuel',
    age: 1,
    gender: 'male',
    isVaccinated: true,
    isNeutered: true,
    size: 'small',
    breed: 'Jack Russell',
    traits: ['Quiet', 'Great with children'],
    photoUrl: 'https://images.dog.ceo/breeds/brabancon/n02112706_971.jpg',
  },
  {
    name: 'Tillie',
    age: 2,
    gender: 'female',
    isVaccinated: true,
    isNeutered: true,
    size: 'medium',
    breed: 'Collie cross',
    traits: ['Affectionate', 'Loves to play'],
    photoUrl:
      'https://images.dog.ceo/breeds/terrier-lakeland/n02095570_1208.jpg',
  },
  {
    name: 'Barnaby',
    age: 1,
    gender: 'male',
    isVaccinated: false,
    isNeutered: false,
    size: 'large',
    breed: 'Labrador',
    traits: ['Very active', 'Big appetite'],
    photoUrl: 'https://images.dog.ceo/breeds/spitz-japanese/beet-005.jpg',
  },
  {
    name: 'Emily',
    age: 3,
    gender: 'female',
    isVaccinated: false,
    isNeutered: true,
    size: 'small',
    breed: 'Springer Spaniel',
    traits: ['Friendly', 'Great around other dogs'],
    photoUrl:
      'https://images.dog.ceo/breeds/rajapalayam-indian/Rajapalayam-dog.jpg',
  },

  // 26 Additional Puppies
  {
    name: 'Max',
    age: 2,
    gender: 'male',
    isVaccinated: true,
    isNeutered: false,
    size: 'medium',
    breed: 'Beagle',
    traits: ['Playful', 'Energetic'],
    photoUrl: 'https://images.dog.ceo/breeds/terrier-norfolk/n02094114_550.jpg',
  },
  {
    name: 'Bella',
    age: 4,
    gender: 'female',
    isVaccinated: true,
    isNeutered: true,
    size: 'large',
    breed: 'German Shepherd',
    traits: ['Protective', 'Smart'],
    photoUrl:
      'https://images.dog.ceo/breeds/terrier-patterdale/dog-1268559_640.jpg',
  },
  {
    name: 'Cooper',
    age: 3,
    gender: 'male',
    isVaccinated: false,
    isNeutered: true,
    size: 'small',
    breed: 'Chihuahua',
    traits: ['Shy', 'Needs gentle approach'],
    photoUrl:
      'https://images.dog.ceo/breeds/schnauzer-giant/n02097130_4663.jpg',
  },
  {
    name: 'Daisy',
    age: 5,
    gender: 'female',
    isVaccinated: true,
    isNeutered: false,
    size: 'medium',
    breed: 'Poodle',
    traits: ['Loves to cuddle', 'Very smart'],
    photoUrl: 'https://images.dog.ceo/breeds/airedale/n02096051_8019.jpg',
  },
  {
    name: 'Rocky',
    age: 2,
    gender: 'male',
    isVaccinated: true,
    isNeutered: true,
    size: 'medium',
    breed: 'Bulldog',
    traits: ['Calm', 'Good with kids'],
    photoUrl: 'https://images.dog.ceo/breeds/kelpie/n02105412_2650.jpg',
  },
  {
    name: 'Lola',
    age: 6,
    gender: 'female',
    isVaccinated: false,
    isNeutered: true,
    size: 'large',
    breed: 'Golden Retriever',
    traits: ['Gentle', 'Great with families'],
    photoUrl: 'https://images.dog.ceo/breeds/corgi-cardigan/n02113186_7600.jpg',
  },
  {
    name: 'Winston',
    age: 1,
    gender: 'male',
    isVaccinated: true,
    isNeutered: false,
    size: 'small',
    breed: 'Dachshund',
    traits: ['Curious', 'Good on leash'],
    photoUrl: 'https://images.dog.ceo/breeds/australian-shepherd/sadie.jpg',
  },
  {
    name: 'Luna',
    age: 4,
    gender: 'female',
    isVaccinated: true,
    isNeutered: true,
    size: 'large',
    breed: 'Husky',
    traits: ['Very active', 'Talkative'],
    photoUrl: 'https://images.dog.ceo/breeds/mastiff-bull/n02108422_4445.jpg',
  },
  {
    name: 'Toby',
    age: 2,
    gender: 'male',
    isVaccinated: false,
    isNeutered: false,
    size: 'small',
    breed: 'Corgi',
    traits: ['Happy', 'Loves short walks'],
    photoUrl:
      'https://images.dog.ceo/breeds/retriever-golden/n02099601_569.jpg',
  },
  {
    name: 'Coco',
    age: 7,
    gender: 'female',
    isVaccinated: false,
    isNeutered: true,
    size: 'medium',
    breed: 'Rottweiler',
    traits: ['Calm', 'Good guard dog'],
    photoUrl: 'https://images.dog.ceo/breeds/keeshond/n02112350_6861.jpg',
  },
  {
    name: 'Buddy',
    age: 3,
    gender: 'male',
    isVaccinated: true,
    isNeutered: true,
    size: 'large',
    breed: 'Boxer',
    traits: ['Energetic', 'Loves to run'],
    photoUrl: 'https://images.dog.ceo/breeds/setter-english/n02100735_9936.jpg',
  },
  {
    name: 'Molly',
    age: 1,
    gender: 'female',
    isVaccinated: true,
    isNeutered: false,
    size: 'small',
    breed: 'Shih Tzu',
    traits: ['Affectionate', 'Lap dog'],
    photoUrl: 'https://images.dog.ceo/breeds/schipperke/n02104365_8525.jpg',
  },
  {
    name: 'Leo',
    age: 5,
    gender: 'male',
    isVaccinated: true,
    isNeutered: true,
    size: 'medium',
    breed: 'Pitbull',
    traits: ['Strong', 'Very loyal'],
    photoUrl: 'https://images.dog.ceo/breeds/whippet/n02091134_16420.jpg',
  },
  {
    name: 'Rosie',
    age: 2,
    gender: 'female',
    isVaccinated: false,
    isNeutered: true,
    size: 'large',
    breed: 'Great Dane',
    traits: ['Gentle giant', 'Low energy'],
    photoUrl: 'https://images.dog.ceo/breeds/kuvasz/n02104029_2504.jpg',
  },
  {
    name: 'Archie',
    age: 4,
    gender: 'male',
    isVaccinated: true,
    isNeutered: false,
    size: 'small',
    breed: 'Pug',
    traits: ['Goofy', 'Loves attention'],
    photoUrl: 'https://images.dog.ceo/breeds/african/n02116738_9333.jpg',
  },
  {
    name: 'Lucy',
    age: 6,
    gender: 'female',
    isVaccinated: true,
    isNeutered: true,
    size: 'medium',
    breed: 'Border Collie',
    traits: ['Highly active', 'Needs space to run'],
    photoUrl: 'https://images.dog.ceo/breeds/kelpie/n02105412_7634.jpg',
  },
  {
    name: 'Milo',
    age: 1,
    gender: 'male',
    isVaccinated: false,
    isNeutered: false,
    size: 'small',
    breed: 'Yorkshire Terrier',
    traits: ['Alert', 'Vocal'],
    photoUrl: 'https://images.dog.ceo/breeds/mastiff-bull/n02108422_1442.jpg',
  },
  {
    name: 'Bailey',
    age: 3,
    gender: 'female',
    isVaccinated: true,
    isNeutered: false,
    size: 'large',
    breed: 'Bernese Mountain Dog',
    traits: ['Very fluffy', 'Mild temperament'],
    photoUrl: 'https://images.dog.ceo/breeds/spitz-indian/Indian_Spitz.jpg',
  },
  {
    name: 'Dexter',
    age: 2,
    gender: 'male',
    isVaccinated: true,
    isNeutered: true,
    size: 'medium',
    breed: 'French Bulldog',
    traits: ['Playful', 'Snorts a lot'],
    photoUrl:
      'https://images.dog.ceo/breeds/spaniel-japanese/n02085782_3870.jpg',
  },
  {
    name: 'Ruby',
    age: 8,
    gender: 'female',
    isVaccinated: true,
    isNeutered: true,
    size: 'small',
    breed: 'Maltese',
    traits: ['Loves laps', 'Low shedding'],
    photoUrl:
      'https://images.dog.ceo/breeds/terrier-bedlington/n02093647_2477.jpg',
  },
  {
    name: 'Finn',
    age: 1,
    gender: 'male',
    isVaccinated: false,
    isNeutered: false,
    size: 'medium',
    breed: 'Dalmatian',
    traits: ['High energy', 'Loves running'],
    photoUrl: 'https://images.dog.ceo/breeds/pekinese/n02086079_7769.jpg',
  },
  {
    name: 'Sophie',
    age: 5,
    gender: 'female',
    isVaccinated: true,
    isNeutered: false,
    size: 'large',
    breed: 'Doberman',
    traits: ['Alert', 'Very trainable'],
    photoUrl: 'https://images.dog.ceo/breeds/shihtzu/n02086240_12315.jpg',
  },
  {
    name: 'Harvey',
    age: 3,
    gender: 'male',
    isVaccinated: true,
    isNeutered: true,
    size: 'small',
    breed: 'Cocker Spaniel',
    traits: ['Friendly', 'Eager to please'],
    photoUrl: 'https://images.dog.ceo/breeds/chow/n02112137_6282.jpg',
  },
  {
    name: 'Zoe',
    age: 2,
    gender: 'female',
    isVaccinated: false,
    isNeutered: true,
    size: 'medium',
    breed: 'Greyhound',
    traits: ['Fast runner', 'Gentle indoors'],
    photoUrl: 'https://images.dog.ceo/breeds/doberman/n02107142_4763.jpg',
  },
  {
    name: 'Bruno',
    age: 4,
    gender: 'male',
    isVaccinated: true,
    isNeutered: false,
    size: 'large',
    breed: 'Australian Shepherd',
    traits: ['Very intelligent', 'Needs mental stimulation'],
    photoUrl: 'https://images.dog.ceo/breeds/mexicanhairless/n02113978_304.jpg',
  },
  {
    name: 'Maggie',
    age: 7,
    gender: 'female',
    isVaccinated: true,
    isNeutered: true,
    size: 'small',
    breed: 'Boston Terrier',
    traits: ['Friendly', 'Moderate exercise needs'],
    photoUrl:
      'https://images.dog.ceo/breeds/bulldog-boston/20200710_175944.jpg',
  },
];
